### PR TITLE
Add Vue 3 & Nuxt 3 support

### LINKED ISSUE #61: Nuxt 3 support
Trying to use it with Nuxt 3 and getting error
`index.js:1600 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'peekGutter')`

### PR DESCRIPTION
**Pull request by weotch**
Fixes #61, #69

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203536584348213

### CODE REVIEW

**Comment by nathanchase** [comment]
Can't wait to try this in my Nuxt 3 project!

**Comment by dejanbabic** [comment]
Hi @weotch any news?

**Comment by aleksandar-brkic** [comment]
@weotch Is this going to be realised for Nuxt 3?

**Comment by aleksandar-brkic** [comment]
@weotch @DarkSupah Is this going to be realised for Nuxt 3?

**Pull request closed without merging**
