### PR TITLE
Fix peeking with disabled state

### LINKED ISSUE #95: Issue with disabling behavior when a peek and loop are specified
Hi there. I noticed that setting `slidesPerPage` in `responsive` a value that is equal or higher than the carousel length, while the `loop` is `true`, will break the carousel. In this case, I think `slidesPerPage` value should at least default to the carousel length value - 1. What do you guys think?

This is how is displayed: 
image

### PR DESCRIPTION
**Pull request by weotch**
Fixes #95

### CODE REVIEW

**Comment by weotch** [comment]
@fgrasu can you let me know if this fixes your issue from #95?  You can use this branch if you change your version constraint to `vue-ssr-carousel: BKWLD/vue-ssr-carousel#dbdff2cc`

**Comment by fgrasu** [comment]
hi @weotch, thanks for working on this issue. it's a partially fix, if you remove the `:slides-per-pages="4"` from default props or if you have another `slidesPerPage` in `responsive`, something like this: 
image
then the carousel is still broken. 
btw, I used your branch as a version like you said but I didn't get the changes, I applied the style changes manually. maybe I did something wrong idk.

**Comment by weotch** [comment]
[I couldn't reproduce](https://codesandbox.io/p/github/BKWLD/vue-ssr-carousel/fix-peeking-with-disabled-state?file=%2Fdemo%2Fcomponents%2Fdemos%2Fmisc%2Fdisabling.vue&selection=%5B%7B%22endColumn%22%3A22%2C%22endLineNumber%22%3A18%2C%22startColumn%22%3A22%2C%22startLineNumber%22%3A18%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8f9yme4003llpjv0r4b39do%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fdemo%252Fcomponents%252Fdemos%252Fmisc%252Fdisabling.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522PR%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl8f9zoc400cf3b6igz0ko6ab%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Fmisc%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl8f9zm3z00ab3b6iskombqz9%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D) the issue you're mentioning with those props.

It looks wonky, but that's just because it's trying to cram 10 in that space.

image
image

**Comment by fgrasu** [comment]
Oh.. I was thinking that, if the `slidesPerPage` value is higher that the carousel length, it should take the carousel length value instead. that way will not look wonky, it will display 2 slides to fill the viewport (without peeking, if any is set, because doesn't make sense in this case).
In your code above, can you try to delete the `:slides-per-pages="4"` from default props? there are no slides displayed. Can you reproduce that?

**Comment by weotch** [comment]
> Oh.. I was thinking that, if the slidesPerPage value is higher that the carousel length, it should take the carousel length value instead. that way will not look wonky, it will display 2 slides to fill the viewport (without peeking, if any is set, because doesn't make sense in this case).

I think with same layouts, you'd want the width of the slides to be consistent, even if there weren't enough to fill the carousel width.  Like maybe you don't want to scale up a slide to 100% if there was only one.  If you are rendering your slides with a `v-for`, I think you could accomplish what you're after with:

```vue
<ssr-carousel :slides-per-page='Math.min(10, slides.length)'>
  <slide v-for='for slide in slides' />
</ssr-carousel>
```

> In your code above, can you try to delete the :slides-per-pages="4" from default props? there are no slides displayed. Can you reproduce that?

[Still seems fine to me](https://codesandbox.io/p/github/BKWLD/vue-ssr-carousel/fix-peeking-with-disabled-state?file=%2Fdemo%2Fcomponents%2Fdemos%2Fmisc%2Fdisabling.vue&selection=%5B%7B%22endColumn%22%3A5%2C%22endLineNumber%22%3A14%2C%22startColumn%22%3A5%2C%22startLineNumber%22%3A14%7D%5D&workspace=%257B%2522activeFileId%2522%253A%2522cl8f9yme4003llpjv0r4b39do%2522%252C%2522openFiles%2522%253A%255B%2522%252FREADME.md%2522%252C%2522%252Fdemo%252Fcomponents%252Fdemos%252Fmisc%252Fdisabling.vue%2522%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522PR%2522%252C%2522sidekickItems%2522%253A%255B%257B%2522type%2522%253A%2522PREVIEW%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522key%2522%253A%2522cl8f9zoc400cf3b6igz0ko6ab%2522%252C%2522isMinimized%2522%253Afalse%252C%2522path%2522%253A%2522%252Fmisc%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522key%2522%253A%2522cl8f9zm3z00ab3b6iskombqz9%2522%252C%2522isMinimized%2522%253Afalse%257D%255D%257D), unless codesandbox isn't updating like it should.

image

**Comment by fgrasu** [comment]
It seems like if you set `:peek="0"` with 0 as a string you might have some issues. that's why you couldn't reproduce my scenario. so either `:peek="0"` or `:peek="'0px'"` will work just fine. 
Thanks for patience. I'm good with your PR solution

**Pull request merged**
