### PR TITLE
Remove console log

### PR DESCRIPTION
**Pull request by lemoswilson**
Just noticed that I did not remove a console log call I had added to inspect the code 😅  sorry bout that. 

I can publish a new package version myself if you are ok with that, just let me know.

### CODE REVIEW

**Comment by weotch** [comment]
Oh yeah, go ahead on publish 👍

**Comment by lemoswilson** [comment]
image

Turns out I can't publish this one package, maybe it's not under the npm bklwd org?

**Comment by weotch** [comment]
I published it this morning but I also added you to npm for the package as well

**Comment by lemoswilson** [comment]
Nice, thanks!

**Pull request merged**
